### ISSUE TITLE
ClientError: /services.verifiablecredentials.v1.VerifiableCredential/Send INTERNAL: Name or service not known ErrorCode: HostNotFound (ServiceCommunicationProblem)

### ISSUE THREAD

**Issue by dnaicker** [Dentity-Development/dentity-ecosystems-sdk#1198]
### Reproduction steps

Receiving the following error when trying to utilise send credential to email api call.

1. Using:
```
const credential_id = await trinsic.credential().send(SendRequest.fromPartial({
	email: (request.payload as any).account_email,
	documentJson: credential.documentJson,
}))
```
2. Error response:
```
ClientError: /services.verifiablecredentials.v1.VerifiableCredential/Send INTERNAL: Name or service not known ErrorCode: HostNotFound (ServiceCommunicationProblem)
    at wrapClientError (C:\Users\denai\Github\Express\hapi_typescript\node_modules\nice-grpc\lib\client\wrapClientError.js:9:16)
    at Object.callback (C:\Users\denai\Github\Express\hapi_typescript\node_modules\nice-grpc\lib\client\createUnaryMethod.js:27:66)
    at Object.onReceiveStatus (C:\Users\denai\Github\Express\hapi_typescript\node_modules\@grpc\grpc-js\build\src\client.js:195:36)
    at Object.onReceiveStatus (C:\Users\denai\Github\Express\hapi_typescript\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:365:141)  
    at Object.onReceiveStatus (C:\Users\denai\Github\Express\hapi_typescript\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:328:181)  
    at C:\Users\denai\Github\Express\hapi_typescript\node_modules\@grpc\grpc-js\build\src\call-stream.js:188:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  path: '/services.verifiablecredentials.v1.VerifiableCredential/Send',
  code: 13,
  details: 'Name or service not known ErrorCode: HostNotFound (ServiceCommunicationProblem)'
}
```

**Comment by janpieterz** [comment]
Hi @dnaicker, thanks for reporting. I'm looking into the issue as we speak, it's something on our end.

**Comment by janpieterz** [comment]
Hi @dnaicker, this should be resolved. It was a perfect storm of some unimportant errors causing us not to detect this issue. Apologies for the inconvenience.

**Comment by dnaicker** [comment]
Thanks 
JP it works now!

I noticed I don't receive a response message only an empty object {}, is this correct?

If so I can then just create a success message for the user.

**Comment by tmarkovski** [comment]
> I noticed I don't receive a response message only an empty object {}, is this correct?

That's correct. That endpoint [has no fields](https://docs.trinsic.id/reference/services/credential-service/#__tabbed_13_3) in the response message.
